apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    name: {{ .Values.app_name }}
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: {{ print .Values.name ":" .Values.version | quote }}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
    - type: ConfigChange
status:
  lastVersion: 0
