kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ .Values.app_name | quote }}
spec:
  strategy:
    type: Rolling
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - {{ .Values.name | quote }}
        from:
          kind: ImageStreamTag
          name: {{ print .Values.name ":" .Values.version | quote }}
    - type: ConfigChange
  replicas: 1
  selector:
    name: {{ .Values.name | quote }}
  template:
    metadata:
      name: {{ .Values.name | quote }}
      labels:
        name: {{ .Values.name | quote }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ print .Values.name ":" .Values.version | quote }}
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: {{ .Values.memory_limit | quote }}
          envFrom:
            - configMapRef:
                name: {{ print .Values.name "-config" }}
          volumeMounts:
            - mountPath: /index
              name: index
      volumes:
        - emptyDir: {}
          name: index
