spring:
  jpa:
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
  servlet.multipart:
    maxFileSize: 200MB
    maxRequestSize: 200MB

  data:
    mongodb:
      database: recipes

management.endpoint:
  metrics.enabled: true
  prometheus.enabled: true
management.metrics.export.prometheus.enabled: true
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  endpoint:
    health:
      show-details: always
