server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://docker.local:5432/washeuteessen
    password: password
    username: postgres

  data:
    mongodb:
      uri: mongodb://docker.local:27017

washeuteessen.management:
  # every hour
  mongoImportCron: 0 0 * * * *
