spring:
  jpa:
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: true
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:file:./index/database;DB_CLOSE_ON_EXIT=FALSE

  h2.console.enabled: true
  h2.console.path: /h2-console
