server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://docker.local:5432/washeuteessen
    password: password
    username: postgres

  data:
    mongodb:
      uri: mongodb://docker.local:27017

washeuteessen:
  # every hour
  management.mongoImportCron: 0 0 * * * *
  # sitemap stuff
  sitemap:
    enabled: true
    publicHost: localhost
    publicScheme: http
    publicContext:
    searchTemplate: "http://localhost:4200/#/search?s=%s"
    # every minute
    generationCron: 0 * * * * *
    generationPath: ./sitemap
